---
# vars file for install-service
ansible_host_key_checking: False
ansible_become: yes
ansible_become_method: sudo
ansible_become_pass: "{{ lookup('vars',host_pass_var) if host_pass_var is defined else None }}"
ansible_ssh_user: "{{ host_user if host_user is defined else 'admin' }}" 
ansible_ssh_pass: "{{ lookup('vars',host_pass_var) if host_pass_var is defined else None }}"
base_dir: "{% if sw_version is defined %}{{ local_dir }}/{{ credentials.node_ip }}/{{ sw_version }}{% else %}{{ local_dir }}/{{ credentials.node_ip }}{% endif %}"
reinstall_flag: "{{ reinstall if reinstall is defined else 'false'|bool }}"
